version: '2'
services:
    clubplanner-app:
        image: clubplanner
        external_links:
            - clubplanner-postgresql:postgresql
            - clubplanner-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/clubplanner
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    clubplanner-postgresql:
        extends:
            file: postgresql.yml
            service: clubplanner-postgresql
    clubplanner-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: clubplanner-elasticsearch
